
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 24 20:48:03 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 41;
  public static final int NOT_EQUAL_TO = 17;
  public static final int CONST = 4;
  public static final int LESS_THAN_OR_EQUAL = 21;
  public static final int LPAREN = 30;
  public static final int NUM_CONST = 39;
  public static final int GREATER_THAN = 18;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 27;
  public static final int COMMA = 28;
  public static final int INC = 25;
  public static final int DIV = 14;
  public static final int QUESTION_MARK = 36;
  public static final int IF = 5;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 24;
  public static final int LOGICAL_OR = 23;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int ADD = 11;
  public static final int MOD = 15;
  public static final int IDENT = 38;
  public static final int VOID = 10;
  public static final int EQUAL_TO = 16;
  public static final int COLON = 37;
  public static final int LBRACE = 34;
  public static final int ELSE = 3;
  public static final int LSQUARE = 32;
  public static final int READ = 8;
  public static final int GOTO = 42;
  public static final int RSQUARE = 33;
  public static final int LOGICAL_AND = 22;
  public static final int RBRACE = 35;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 40;
  public static final int GREATER_THAN_OR_EQUAL = 19;
  public static final int DEC = 26;
  public static final int LESS_THAN = 20;
  public static final int SUB = 12;
  public static final int PRINT = 7;
}

